name: Continous Integration

on: [push, pull_request,workflow_dispatch]

jobs:
  test-browser:
    name: Browser tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm
      - name: npm install
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test-ci

  test-node:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        node-version:
          - 10 # minimum supported version
          - 14 # current LTS
          - 16 # latest
    name: Node.js ${{ matrix.node-version }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test-node

  test-typings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ts-version:
          - '3.0'
          - '4.0'
          - 'latest'
    name: Typings tests (typescript@${{ matrix.ts-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm
      - name: npm install
        run: npm install
      - name: Install typescript@${{ matrix.ts-version }}
        run: |
          npm install typescript@${{ matrix.ts-version }}
          # fix: if latest, also install matching node types
          if [ "${{ matrix.ts-version }}" = "latest" ]; then
            npm install @types/node@latest
          fi
      - name: Run tests
        run: npm run test-typings

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm
      - name: npm install
        run: npm install
      - name: Check Prettier
        run: npm run lint
